### ISSUE TITLE
Pre-Commit requirements

### ISSUE THREAD

**Issue by tulilirockz** [ublue-os/bext#13]
This may help out as linting and making sure the code actually runs before commiting is very helpful :)

**Comment by bketelsen** [comment]
golangci-lint is great for this

**Comment by tulilirockz** [comment]
We could have both Pre-commit and that, for an added layer of safety

**Comment by bketelsen** [comment]
great idea!
I added golangci-lint, and it already found some errors!

**Comment by tulilirockz** [comment]
There are some of those that were proposital, like the "syscall.Unmount was not checked!", because I just wanted to ignore errors in that syscall, but everything else is indeed required

**Comment by bketelsen** [comment]
for ones you want to ignore, just assign the error return value to `_`

I did that for the ones I assumed you wanted to ignore. Did I miss any?

**Comment by tulilirockz** [comment]
Nope! You got all of them! Its alright!
